apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-httpd-deployment
    annotations:
       # argocd.argoproj.io/hook: Sync
       argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 3
  selector:
      matchLabels:
            app: frontend
  template:
     metadata:
         labels:
            app: frontend
     spec:
       containers:
            - name: c01
              image: httpd
              ports:
                - containerPort: 80
